apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: add
 namespace: default
spec:
 template:
  spec:
   securityContext:
    allowPrivilegeEscalation: "false"
   containers:
    - image: gcr.io/knative-samples/helloworld-go
      env:
        - name: TARGET
          value: "add capabilities"
      securityContext:
        allowPrivilegeEscalation: "false"
        #capabilities:
        #  add:
        #    - NET_BIND_SERVICE
        #    - CAP_SYS_ADMIN
