apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: dug-bug 
 namespace: default
spec:
 template:
  spec:
   containers:
    - image: psschwei/helloworld-go
      env:
        - name: TARGET
          value: "Go Sample v1"
