apiVersion: v1
kind: ResourceQuota
metadata:
  name: knative-rq
spec:
  hard:
    cpu: 50m
---
apiVersion: v1
kind: LimitRange
metadata:
  name: knative-limit
spec:
  limits:
  - max:
      cpu: "800m"
    min:
      cpu: "200m"
    type: Container
