apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: hello
spec:
 template:
  metadata:
    annotations:
      autoscaling.knative.dev/metric: "rps"
  spec:
   containers:
    - image: gcr.io/knative-samples/helloworld-go
      env:
        - name: TARGET
          value: "Go Sample v2"
