apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: minscale 
 namespace: default
spec:
 template:
  metadata:
    annotations:
      autoscaling.knative.dev/initialScale: "2}"
  spec:
   containers:
    - image: gcr.io/knative-samples/helloworld-go
      env:
        - name: TARGET
          value: "minscale=1"
